					</div>
					<div class="content_bottom"></div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="setlinks">
				<? require_once( 'http://testea.ru/setlinks/slsimple.php?host=' . urlencode( $_SERVER['HTTP_HOST'] ) . '&uri=' . urlencode( $_SERVER['REQUEST_URI'] ) ); ?>
			</div>
			<div class="footer">
				<div class="footer_top">
					<a href="index.php">Силовые тренажеры BodySolid</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="articles.php">Особенности</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="about.php">Где купить</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="subscribe.php">Прайс-лист</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="links.php">Ссылки</a>
				</div>
				<div class="footer_bottom">
					Copyright © <?= date('Y') ?> Body Solid. All rights reserved. <a href="https://www.free-lance.ru/users/Mayber/" target="_blank">Дизайн - May Ber</a>
				</div>
				<div class="footer_counter">
					<!--LiveInternet counter--><script type="text/javascript">document.write("<a href='http://www.liveinternet.ru/click' target=_blank><img src='http://counter.yadro.ru/hit?t14.2;r" + escape(document.referrer) + ((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth)) + ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=88 height=31 alt='' title='LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодн\я'><\/a>")</script><!--/LiveInternet-->
				</div>
			</div>
		</div>
	</body>
</html>
