							</td>
						</tr>
						<tr>
							<td style="width: 280px">
								&nbsp;
							<td style="width: 700px">
								<p class="setlinks"><? require_once( 'http://testea.ru/setlinks/slsimple.php?host=' . urlencode( $_SERVER['HTTP_HOST'] ) . '&uri=' . urlencode( $_SERVER['REQUEST_URI'] ) ); ?></p>
							</td>
						</tr>
						<tr>
							<td colspan="2" style="width: 980px; height: 55px; background-image: url(/images/design/design_r3_c1.jpg)">
								<table cellpadding="0" cellspacing="0" style="width: 100%">
									<tr>
										<td style="width: 270px" align="center">
											<noindex>
<!--LiveInternet counter--><script type="text/javascript">document.write("<a href='http://www.liveinternet.ru/click' target=_blank><img src='http://counter.yadro.ru/hit?t14.2;r" + escape(document.referrer) + ((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth)) + ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=88 height=31 alt='' title='LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодн\я'><\/a>")</script><!--/LiveInternet-->

<!--begin of Rambler's Top100 code -->
<a href="http://top100.rambler.ru/top100/">
<img src="http://counter.rambler.ru/top100.cnt?1081945" alt="" width=1 height=1 border=0></a>
<!--end of Top100 code-->

<!--begin of Top100 logo-->
<a href="http://top100.rambler.ru/top100/">
<img src="http://top100-images.rambler.ru/top100/banner-88x31-rambler-gray2.gif" alt="Rambler's Top100" width=88 height=31 border=0></a>
<!--end of Top100 logo -->
											</noindex>
										</td>
										<td>
											<p class="c"><a href="index.php">Силовые тренажеры BodySolid</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="articles.php">Особенности</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="about.php">Где купить</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="subscribe.php">Прайс-лист</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="links.php">Ссылки</a></p>
											<p class="c" style="color: gray; margin-top: 2px">Copyright ©2007 Body Solid. All rights reserved.</p>
										</td>
										<td style="width: 170px">
											<img src="/images/design/space.gif" usemap="#disigner" style="width: 100%; height: 40px" border="1" alt=""/>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<div style="display: none">
			<noindex>
				<map name="disigner" id="disigner">
					<area shape="rect" coords="0,0,170,40" href="http://asv-design.ru/" title="Дизайн-Студия Алексея Сушкова «ASV-Design»" alt="Дизайн-Студия Алексея Сушкова «ASV-Design»" />
				</map>
			</noindex>
		</div>
	</body>
</html>

