					</div>
					<div class="content_bottom"></div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="setlinks">
				<? require_once( 'http://testea.ru/setlinks/slsimple.php?host=' . urlencode( $_SERVER['HTTP_HOST'] ) . '&uri=' . urlencode( $_SERVER['REQUEST_URI'] ) ); ?>
			</div>
			<div class="footer">
				<div class="footer_top">
					<a href="index.php">Силовые тренажеры BodySolid</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="articles.php">Особенности</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="about.php">Где купить</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="subscribe.php">Прайс-лист</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="links.php">Ссылки</a>
				</div>
				<div class="footer_bottom">
					Copyright © <?= date('Y') ?> Body Solid. All rights reserved.
				</div>
			</div>
		</div>
	</body>
</html>
