<h1>Силовое оборудование от BodySolid.RU - только проверенное качество!</h1>
<img src="images/people.gif" height="190" class="product" alt="БодиСолид - Ваш успех!" title="БодиСолид - Ваш успех!" style="float: right; margin: 5px 0px 0px 10px"/>

<p class="p">ООО "Фитнесспорт" предлагает <a href="products.php?tab=group&group_id=6">тренажеры BodySolid</a> <b>по лучшим ценам</b>. Специальные <a href="http://wnqsport.ru/dealers.php">скидки оптовым покупателям</a> и помощь в <a href="products.php?tab=group&group_id=1">оборудовании фитнес-центров</a> лучшими <a href="products.php?tab=category&category_id=30">профессиональными тренажерами</a>, опытные менеджеры-консультанты и <b>оптимальные сроки поставок</b> - все это к услугам наших клиентов! Звоните нам по телефонам в Москве - (495) 518-14-19, (495) 518-52-97 и в Киеве - (044) 384-06-64, (068) 199-18-85, (096) 444-23-64. Заказ он-лайн для жителей Украины - на сайте <a href="http://fitnessport.com.ua/">Fitnessport.com.ua/</a></p>

<p class="p">ООО "Фитнесспорт" реализует <b><u>"железо"</u></b> оптом и в розницу. Всегда в наличие <b>диски, грифы, гантели</b> и другие утяжелители. Мы поможем подобрать оптимальный комплект "железа" как для индивидуальных тренировок, так и для залов. Подробнее наш ассортимент перечислен к <a href="/products.php?tab=category&category_id=52">каталоге</a>.</p>

<p class="p">У нас - <b>скидки <u>от 10%</u></b> на все <a href="products.php?tab=group&group_id=10">профессиональное спортивное оборудование</a></p>
<br />
<h2>Рекомендуем для ваших тренировок:</h2>

<table cellpadding="2" cellspacing="0"  style="width: 100%; margin-top: 10px">
	<tr align="center" valign="top">
		<td style="width: 33%">
			<p class="c"><a href="products.php?tab=product&product_id=1283">Гантельный ряд от 2.5 до 25 кг</a></p>
		</td>
		<td style="width: 34%">
			<p class="c"><a href="products.php?tab=product&product_id=1271">Цветные олимпийские диски в ассортименте</a></p>
		</td>
		<td style="width: 33%">
			<p class="c"><a href="products.php?tab=product&product_id=1282">Степ-платформа FT-STP-TJ</a></p>
		</td>
	</tr>
	<tr align="center" valign="bottom">
		<td>
			<a href="products.php?tab=product&product_id=1283"><img src="/images/products/preview/p1283.jpg" class="product" alt="Гантельный ряд от 2.5 до 25 кг" title="Гантельный ряд от 2.5 до 25 кг"/></a>
		</td>
		<td>
			<a href="products.php?tab=product&product_id=1271"><img src="/images/products/preview/p1271.jpg" class="product" alt="Цветные олимпийские диски в ассортименте" title="Цветные олимпийские диски в ассортименте"/></a>
		</td>
		<td>
			<a href="products.php?tab=product&product_id=1282"><img src="/images/products/preview/p1282.jpg" class="product" alt="Степ-платформа FT-STP-TJ" title="Степ-платформа FT-STP-TJ"/></a>
		</td>
	</tr>
	<tr align="center" valign="top">
		<td>
			<p class="c" style="margin-bottom: 20px">Гантельный ряд обрезиненный. 10 пар, от 2.5 до 25 кг.</p>
		</td>
		<td>
			<p class="c" style="margin-bottom: 20px">Олимпийские диски с отверстиями для рук, от 2.5 до 25 кг.</p>
		</td>
		<td>
			<p class="c" style="margin-bottom: 20px">Степ-платформа с регулированием уровня высоты.</p>
		</td>
	</tr>
<!-- Второй ряд -->
	<tr align="center" valign="top">
		<td style="width: 33%">
			<p class="c"><a href="products.php?tab=product&product_id=991">Стойка гантельная DR-14</a></p>
		</td>
		<td style="width: 34%">
			<p class="c"><a href="products.php?tab=product&product_id=950">Гантельный ряд D-04</a></p>
		</td>
		<td style="width: 33%">
			<p class="c"><a href="products.php?tab=product&product_id=1262">Замки для грифов</a></p>
		</td>
	</tr>
	<tr align="center" valign="bottom">
		<td>
			<a href="products.php?tab=product&product_id=991"><img src="/images/products/preview/p991.jpg" class="product" alt="Стойка гантельная DR-14" title="Стойка гантельная трехъярусная"/></a>
		</td>
		<td>
			<a href="products.php?tab=product&product_id=950"><img src="/images/products/preview/p950.jpg" class="product" alt="Гантельный ряд D-04" title="Гантельный ряд D-04"/></a>
		</td>
		<td>
			<a href="products.php?tab=product&product_id=1262"><img src="/images/products/preview/p1262.jpg" class="product" alt="Замки для грифов" title="Замки для грифов"/></a>
		</td>
	</tr>
	<tr align="center" valign="top">
		<td>
			<p class="c" style="margin-bottom: 20px">Стойка гантельная трехъярусная.</p>
		</td>
		<td>
			<p class="c" style="margin-bottom: 20px">Гантельный ряд 10 пар, профессиональный, хромированный.</p>
		</td>
		<td>
			<p class="c" style="margin-bottom: 20px">Замки для крепления дисков на грифах.</p>
		</td>
	</tr>
</table>

<p class="p">Более 20 лет продукция <a href="products.php?tab=group&group_id=2"><b>Body Solid</b></a> используется для занятий
<b>бодибилдингом</b> и улучшает качество жизни людей во всем
мире. Более <b>5 миллионов клиентов Body-Solid</b> имеют
ощутимые результаты силовых тренировок, значительно
помогающие в повседневной жизни. Если вы хотите иметь
стройную талию, развитые мышцы груди, сильную спину,
мускулистые руки и мощные ноги, силовые тренировки с помощью <a  href="products.php?tab=category&category_id=35">профессионального оборудования
<b>BodySolid</b></a> являются самым быстрым и эффективным
способом.</p>

<p class="p">Наличие качественного тренажера повышает очень важный аспект силовых тренировок: мотивацию. <b>Высокая мотивация</b> позволяет бесконечно совершенствовать свое тело. С помощью наших <a href="products.php?tab=category&category_id=42">тренажеров</a> Вы избавитесь от лишних килограммов, заменив их упругой мышечной массой. Утомление останется в прошлом, так как ваша выносливость будет расти после каждой тренировки. День за днем <b>Body Solid</b> приведет Вас к успеху!</p>
<br/>
<h2>Лучшие модели нашей коллекции:</h2>

<table cellpadding="2" cellspacing="0"  style="width: 100%; margin-top: 10px">
	<tr align="center" valign="top">
		<td style="width: 45%">
			<p class="c"><a href="products.php?tab=product&product_id=59"> Мультистанция BodySolid G9S</a></p>
		</td>
		<td style="width: 10%" />
		<td style="width: 45%">
			<p class="c"><a href="products.php?tab=product&product_id=708">  Силовой тренажер BodySolid DPEC-SF</a></p>
		</td>
	</tr>
	<tr align="center" valign="bottom">
		<td>
			<a href="products.php?tab=product&product_id=59"><img src="/images/products/preview/p59.jpg" class="product" alt=" Мультистанция BodySolid G9S" title="Мультистанция BodySolid G9S"/></a>
		</td>
		<td style="width: 10%">
                        <img src="images/logo_v.jpg" width="31" height="147" alt="БодиСолид - сделано для жизни">
		</td>
		<td>
			<a href="products.php?tab=product&product_id=708"><img src="/images/products/preview/p708.jpg" class="product" alt=" Силовой тренажер BodySolid DPEC-SF" title=" Силовой тренажер BodySolid DPEC-SF"/></a>
		</td>
	</tr>
	<tr align="center" valign="top">
		<td>
			<p class="c" style="margin-bottom: 20px">Многофункциональный тренажёр с двумя весовыми стеками по 95 кг.</p>
		</td>
		<td style="width: 10%" />
		<td>
			<p class="c" style="margin-bottom: 20px">Профессиональный баттерфляй, позволяющий выполнять упражнения для груди и дельтовидных мышц.</p>
		</td>
	</tr>
</table>